### ISSUE TITLE
Migrations are break

### ISSUE THREAD

**Issue by rkgarcia** [Regulus343/Identify#3]
When run the seedings breaks with error:

     [Illuminate\Database\QueryException]                                                                                                                                   
      SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "test" violates not-null constraint (SQL: insert into "auth_users" ("name", "password", "email",   
       "first_name", "last_name", "created_at", "updated_at", "activated_at") values (Admin, y$LfkP2CWztrZjaUt62j/irOOS/urasmXTyKeZTwsazybhgIl323P1y, admin@localhost.com, A  
      dmin, Istrator, 2015-03-17 06:03:59, 2015-03-17 06:03:59, 2015-03-17 06:03:59) returning "id") 

The test field it's needed? may be with a default value, for example false...

**Comment by Regulus343** [comment]
I have merged your pull request for this. Thank you for the fix.
